#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition main			### specify partition name where to run a job. short: 7 days limit; gtx1080: 7 days; debug: 2 hours limit and 1 job at a time
#SBATCH --time 0-20:00:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name SubGraphsByLabels			### name of the job
#SBATCH --output job-%J.out			### output log for running job - %J for job number
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=5

# Note: the following 4 lines are commented out
#SBATCH --mail-user=yishaiaz@post.bgu.ac.il	### user's email for sending job status messages
#SBATCH --mail-type=END,FAIL			### conditions for sending the email. ALL,BEGIN,END,FAIL, REQUEU, NONE
#SBATCH --mem=20G				### ammount of RAM memory
#SBATCH --tmp=20G


### Print some data to output file ###
## test whether deactivating conda environment in the sbatch script is sufficient
##conda deactivate
## /test whether deactivating conda environment in the sbatch script is sufficient
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your code below ####
#SSD
export SLURM_SCRATCH_DIR=/scratch/${SLURM_JOB_USER}/${SLURM_JOBID}
echo "starting copying raw data to ssd"
cp ~/GBVasculatureGraphsAnalysis/BrainVasculatureGraphData/*.gt $SLURM_SCRATCH_DIR
echo "finished copying raw data to ssd"
echo $SLURM_SCRATCH_DIR
#/SSD
module load anaconda				### load anaconda module (must be present when working with conda environments)
echo "$SLURM_SCRATCH_DIR" >> job_conf_file.txt

source activate /home/yishaiaz/anaconda3/envs/ClearMap				### activate a conda environment, replace my_env with your conda environment
python ./MotifsExplortationCode/PythonScripts/SubGraphsGenerationByAnnotation.py     				### execute python script – replace with your own command
rm job_conf_file.txt
#SSD
cp -r $SLURM_SCRATCH_DIR $SLURM_SUBMIT_DIR
#/SSD
