#!/bin/bash

################################################################################################
### sbatch configuration parameters must start with #SBATCH and must precede any other commands.
### To ignore, just add another # - like so: ##SBATCH
################################################################################################

#SBATCH --partition main			### specify partition name where to run a job. short: 7 days limit; gtx1080: 7 days; debug: 2 hours limit and 1 job at a time
#SBATCH --time 0-23:59:00			### limit the time of job running. Make sure it is not greater than the partition time limit!! Format: D-H:MM:SS
#SBATCH --job-name MotifsAggregating			### name of the job
#SBATCH --output job-%J.out			### output log for running job - %J for job number
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=48

# Note: the following 4 lines are commented out
#SBATCH --mail-user=yishaiaz@post.bgu.ac.il	### user's email for sending job status messages
#SBATCH --mail-type=END,FAIL			### conditions for sending the email. ALL,BEGIN,END,FAIL, REQUEU, NONE
#SBATCH --mem=32G				### ammount of RAM memory

### Print some data to output file ###
echo `date`
echo -e "\nSLURM_JOBID:\t\t" $SLURM_JOBID
echo -e "SLURM_JOB_NODELIST:\t" $SLURM_JOB_NODELIST "\n\n"

### Start your code below ####
#SSD
export SLURM_SCRATCH_DIR=/scratch/${SLURM_JOB_USER}/${SLURM_JOBID}
echo -e "SLURM_SCRATCH_DIR:\t" $SLURM_SCRATCH_DIR "\n\n"

cp ~/GBVasculatureGraphsAnalysis/BrainVasculatureGraphData/torch_data_graph_annotated_subgraph_with_labels $SLURM_SCRATCH_DIR

#/SSD
module load anaconda				### load anaconda module (must be present when working with conda environments)
source activate BrainVasculatureGraphAnalysis				### activate a conda environment, replace my_env with your conda environment
export SCRIPT_NAME=PyTorchCustomUtilitiesForCluster.py
export SCRIPT_PATH=~/GBVasculatureGraphsAnalysis/GNN_Exploration_BIOMARKER_Presence_SCRIPTS/${SCRIPT_NAME}
export CWD=pwd
echo "Working from $CWD"
echo "started with ${SCRIPT_NAME} python script at ${SCRIPT_PATH}"
python ${SCRIPT_PATH}    				### execute python script
echo "done with ${SCRIPT_NAME} python script"
#SSD
cp -r $SLURM_SCRATCH_DIR $SLURM_SUBMIT_DIR
echo -e "COPIED TO SLURM_SUBMIT_DIR:\t" $SLURM_JOB_NODELIST "\n\n"
#/SSD
